# Generated by Django 5.2.17 on 2026-08-14 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('post', '帖子'), ('live', '直播间'), ('voice', '语音房'), ('game', '桌游室'), ('group', '群')], max_length=16, verbose_name='目标类型')),
                ('target_id', models.CharField(max_length=64, verbose_name='目标ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'target_type', 'target_id')},
            },
        ),
    ]
