# Generated by Django 5.2.17 on 2026-08-12 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='直播间标题')),
                ('stream_key', models.CharField(max_length=64, unique=True, verbose_name='推流指纹')),
                ('status', models.CharField(choices=[('idle', 'idle'), ('live', 'live'), ('ended', 'ended')], default='idle', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='最近开播时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='最近下播时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '直播频道',
                'verbose_name_plural': '直播频道',
                'db_table': 'live_channels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Danmaku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, verbose_name='弹幕文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danmaku', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danmaku', to='live.livechannel')),
            ],
            options={
                'verbose_name': '弹幕',
                'verbose_name_plural': '弹幕',
                'db_table': 'live_danmaku',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='livechannel',
            index=models.Index(fields=['owner'], name='live_channels_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='livechannel',
            index=models.Index(fields=['status'], name='live_channels_status_idx'),
        ),
        migrations.AddIndex(
            model_name='livechannel',
            index=models.Index(fields=['created_at'], name='live_channels_created_idx'),
        ),
        migrations.AddIndex(
            model_name='danmaku',
            index=models.Index(fields=['channel', 'created_at'], name='live_danmaku_chan_created_idx'),
        ),
    ]
