# Generated by Django 5.2.17 on 2026-08-14 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechannel',
            name='group',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'group'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_channels', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='livechannel',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('friends', '好友可见'), ('group', '群成员可见')], default='public', max_length=16, verbose_name='可见性'),
        ),
    ]
