# Generated by Django 5.2.17 on 2026-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_livechannel_description_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='danmaku',
            name='media_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='媒体引用'),
        ),
    ]
