# Generated by Django 5.2.17 on 2026-08-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_join_policy'),
        ('live', '0004_danmaku_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechannel',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'group'}, related_name='visible_live_channels', to='chat.conversation'),
        ),
    ]
