# Generated by Django 5.2.17 on 2026-08-11 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='频道名')),
                ('room_name', models.CharField(max_length=128, unique=True, verbose_name='LiveKit Room 名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_voice_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '语音频道',
                'verbose_name_plural': '语音频道',
                'db_table': 'voice_channels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VoiceChannelMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='最近加入时间')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='最近活跃')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='voice.voicechannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '频道成员',
                'verbose_name_plural': '频道成员',
                'db_table': 'voice_channel_members',
                'unique_together': {('channel', 'user')},
            },
        ),
    ]
