# Generated by Django 5.2.17 on 2026-08-17 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_voicechannel_group_voicechannel_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, default='', max_length=2000, verbose_name='消息内容')),
                ('media_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='媒体引用')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发送时间')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='voice.voicechannel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_chat_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
