# Generated by Django 5.2.17 on 2026-09-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_voicechannel_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicechannel',
            name='last_occupied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近有人进入'),
        ),
        migrations.AddField(
            model_name='voicechannel',
            name='last_vacant_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近变空'),
        ),
    ]
