# Generated by Django 5.2.17 on 2026-08-11 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiPack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统包')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '表情包',
                'verbose_name_plural': '表情包',
                'db_table': 'emoji_packs',
            },
        ),
        migrations.CreateModel(
            name='EmojiItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, default='', max_length=64, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_items', to='media.mediaobject')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='emoji.emojipack')),
            ],
            options={
                'verbose_name': '表情项',
                'verbose_name_plural': '表情项',
                'db_table': 'emoji_items',
                'constraints': [models.UniqueConstraint(fields=('pack', 'media'), name='uniq_emoji_pack_media')],
            },
        ),
    ]
