# Generated by Django 5.2.17 (任务 03：群内表情包 —— EmojiPack 增加 group FK 与 allow_member_upload 开关)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_alter_type_poke'),
        ('emoji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojipack',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji_packs', to='chat.conversation', verbose_name='群表情包所属群'),
        ),
        migrations.AddField(
            model_name='emojipack',
            name='allow_member_upload',
            field=models.BooleanField(default=False, verbose_name='允许普通成员上传'),
        ),
    ]
