# Generated by Django 5.2.17 on 2026-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_voice',
            field=models.BooleanField(default=False, verbose_name='正在语音房'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='正在开播'),
        ),
        migrations.AddField(
            model_name='user',
            name='live_room_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='直播间 ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_room_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='语音房 ID'),
        ),
    ]
