# Generated by Django 5.2.17 on 2026-08-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_in_voice_user_is_live_user_live_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_content',
            field=models.BooleanField(default=False, verbose_name='向他人展示内容'),
        ),
    ]
