# Generated by Django 5.2.17 on 2026-08-11 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='媒体ID')),
                ('kind', models.CharField(choices=[('image', '图片'), ('voice', '语音'), ('file', '文件'), ('emoji', '表情')], db_index=True, max_length=16, verbose_name='类型')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希')),
                ('mime_type', models.CharField(blank=True, default='', max_length=128, verbose_name='MIME 类型')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='大小')),
                ('storage_path', models.CharField(blank=True, default='', max_length=256, verbose_name='存储路径')),
                ('status', models.CharField(choices=[('processing', '处理中'), ('ready', '就绪'), ('failed', '失败')], default='processing', max_length=16, verbose_name='状态')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='时长')),
                ('thumbnail_path', models.CharField(blank=True, default='', max_length=256, verbose_name='缩略图路径')),
                ('waveform_path', models.CharField(blank=True, default='', max_length=256, verbose_name='波形图路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '媒体对象',
                'verbose_name_plural': '媒体对象',
                'db_table': 'media_objects',
            },
        ),
        migrations.CreateModel(
            name='MediaUploadSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_id', models.CharField(max_length=64, unique=True, verbose_name='上传ID')),
                ('kind', models.CharField(choices=[('image', '图片'), ('voice', '语音'), ('file', '文件'), ('emoji', '表情')], max_length=16, verbose_name='类型')),
                ('expected_size', models.PositiveBigIntegerField(default=0, verbose_name='声明大小')),
                ('mime_type', models.CharField(blank=True, default='', max_length=128, verbose_name='期望 MIME')),
                ('status', models.CharField(choices=[('pending', '待上传'), ('completed', '已完成'), ('expired', '已过期')], default='pending', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '上传会话',
                'verbose_name_plural': '上传会话',
                'db_table': 'media_upload_sessions',
                'indexes': [models.Index(fields=['owner', 'status'], name='idx_upload_owner_status')],
            },
        ),
    ]
