# Generated by Django 5.2.17 on 2026-08-11 11:35

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediauploadsession',
            name='media_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='完成后的媒体ID'),
        ),
        migrations.AlterField(
            model_name='mediauploadsession',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=apps.media.models.default_expires_at, verbose_name='过期时间'),
        ),
    ]
