# Generated by Django 5.2.17 on 2026-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediauploadsession_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaobject',
            name='kind',
            field=models.CharField(choices=[('image', '图片'), ('voice', '语音'), ('file', '文件'), ('emoji', '表情'), ('video', '视频')], db_index=True, max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='mediauploadsession',
            name='kind',
            field=models.CharField(choices=[('image', '图片'), ('voice', '语音'), ('file', '文件'), ('emoji', '表情'), ('video', '视频')], max_length=16, verbose_name='类型'),
        ),
    ]
