# Generated by Django 5.2.17 on 2026-09-10

# 聊天媒体两级过期标记（docs/architecture/media-storage-expiration.md）：
# - original_expired_at：阶段 1（7 天）原图已删、缩略图保留；
# - expired_at：阶段 2（30 天）完全过期（派生对象已删，记录保留）。
# 两者均 db_index=True（清理命令按此过滤）。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediaobject_kind_alter_mediauploadsession_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='original_expired_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='原图过期时间'),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='expired_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='完全过期时间'),
        ),
    ]
