# Generated by Django 5.2.17 on 2026-08-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_groupinvite_groupjoinrequest'),
        ('media', '0002_mediauploadsession_media_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('public', '公开'), ('friends', '好友可见'), ('group', '群成员可见')], default='public', max_length=16, verbose_name='可见性')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='标题')),
                ('body', models.TextField(blank=True, default='', verbose_name='正文')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(blank=True, limit_choices_to={'type': 'group'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='chat.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'posts',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='posts.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'post_comments',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='media.mediaobject')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
            options={
                'verbose_name': '帖子配图',
                'verbose_name_plural': '帖子配图',
                'db_table': 'post_images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['owner'], name='posts_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['group'], name='posts_group_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='posts_created_idx'),
        ),
    ]
