# Generated by Django 5.2.17 on 2026-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='媒体引用'),
        ),
    ]
