# Generated by Django 5.2.17 on 2026-08-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='评论图片'),
        ),
    ]
