# Generated by Django 5.2.17 on 2026-08-26 (帖子浏览量 + 浏览/已读记录表)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '帖子浏览',
                'verbose_name_plural': '帖子浏览',
                'db_table': 'post_views',
            },
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['user'], name='post_views_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='post_views_unique'),
        ),
    ]
