# Generated by Django 5.2.17 on 2026-08-10 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('private', '私聊'), ('group', '群聊')], max_length=16, verbose_name='类型')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='标题')),
                ('announcement', models.TextField(blank=True, default='', verbose_name='群公告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('voice', '语音'), ('file', '文件'), ('emoji', '表情'), ('system', '系统')], default='text', max_length=16, verbose_name='类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('media_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='媒体引用')),
                ('status', models.CharField(choices=[('sent', '已发送'), ('delivered', '已送达'), ('read', '已读'), ('recalled', '已撤回')], default='sent', max_length=16, verbose_name='状态')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='幂等键')),
                ('seq', models.PositiveBigIntegerField(verbose_name='会话内序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recalled_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'messages',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '已读回执',
                'verbose_name_plural': '已读回执',
                'db_table': 'message_reads',
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', '成员'), ('admin', '管理员'), ('owner', '群主')], default='member', max_length=16, verbose_name='角色')),
                ('muted', models.BooleanField(default=False, verbose_name='禁言')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会话成员',
                'verbose_name_plural': '会话成员',
                'db_table': 'conversation_members',
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='uniq_conv_seq'),
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together={('message', 'user')},
        ),
    ]
