# Generated by Django 5.2.17 on 2026-08-14 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已同意'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='邀请时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.conversation')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invites_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '入群邀请',
                'verbose_name_plural': '入群邀请',
                'db_table': 'group_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, default='', max_length=256, verbose_name='申请消息')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已同意'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='chat.conversation')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_group_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '入群申请',
                'verbose_name_plural': '入群申请',
                'db_table': 'group_join_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
