"""Conversation 增加 avatar 群头像字段（幂等 AddField，迁移系统保证只执行一次）。

avatar 存媒体 content URL（/api/v1/media/{id}/content），空串表示未设置。
"""
# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupinvite_groupjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='群头像'),
        ),
    ]
