# Generated by Django 5.2.17 on 2026-08-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='join_policy',
            field=models.CharField(choices=[('public', '公开加入'), ('application', '申请加入')], default='public', max_length=20, verbose_name='加入方式'),
        ),
    ]
