# Generated by Django 5.2.17 on 2026-08-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_join_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='join_policy',
            field=models.CharField(choices=[('public', '公开加入'), ('application', '申请加入')], default='application', max_length=20, verbose_name='加入方式'),
        ),
    ]
