# Generated by Django 5.2.17 on 2026-08-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groupmemberleavenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='隐藏'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AlterField(
            model_name='groupmemberleavenotice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
