# Generated by Django 5.2.17 on 2026-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversationmember_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('voice', '语音'), ('file', '文件'), ('emoji', '表情'), ('video', '视频'), ('system', '系统')], default='text', max_length=16, verbose_name='类型'),
        ),
    ]
