# Generated by Django 5.2.17 on 2026-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='segments',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='图文段'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('voice', '语音'), ('file', '文件'), ('emoji', '表情'), ('video', '视频'), ('mixed', '图文混排'), ('system', '系统')], default='text', max_length=16, verbose_name='类型'),
        ),
    ]
