# Generated by Django 5.2.17 on 2026-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_groupsubgroup_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='share_payload',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='分享载荷'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('voice', '语音'), ('file', '文件'), ('emoji', '表情'), ('video', '视频'), ('mixed', '图文混排'), ('system', '系统'), ('poke', '戳一戳'), ('share', '分享')], default='text', max_length=16, verbose_name='类型'),
        ),
    ]
