# Generated by Django 5.2.17 on 2026-08-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElysiaProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stream_id', models.CharField(max_length=240, unique=True, verbose_name='Elysium stream_id')),
                ('platform', models.CharField(default='elysia-app', max_length=64, verbose_name='平台标识')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='展示名')),
                ('chat_type', models.CharField(choices=[('private', '私聊'), ('group', '群聊')], default='private', max_length=16, verbose_name='聊天类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elysia_profile', to=settings.AUTH_USER_MODEL, verbose_name='爱莉应用内用户')),
            ],
            options={
                'verbose_name': '爱莉桥接档案',
                'verbose_name_plural': '爱莉桥接档案',
                'db_table': 'elysia_profiles',
            },
        ),
    ]
