# Generated by Django 5.2.17 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elysia_bridge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elysiaprofile",
            name="platform",
            field=models.CharField(
                default="ayla", max_length=64, verbose_name="平台标识"
            ),
        ),
    ]
