# Generated by Django 5.2.17 on 2026-08-12

import hashlib

from django.db import migrations


LEGACY_PLATFORM = "elysia-app"
AYLA_PLATFORM = "ayla"


def _ayla_stream_id(user_id: object) -> str:
    key = f"ayla_{user_id}_private"
    return hashlib.sha256(key.encode("utf-8")).hexdigest()


def migrate_legacy_profiles(apps, schema_editor) -> None:
    """Move only known legacy Ayla profiles off the historical shared stream."""
    ElysiaProfile = apps.get_model("elysia_bridge", "ElysiaProfile")
    for profile in ElysiaProfile.objects.filter(platform=LEGACY_PLATFORM).iterator():
        profile.platform = AYLA_PLATFORM
        profile.stream_id = _ayla_stream_id(profile.user_id)
        profile.save(update_fields=["platform", "stream_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("elysia_bridge", "0002_ayla_platform_default"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_profiles, migrations.RunPython.noop),
    ]
