# Generated by Django 5.2.17 on 2026-08-14 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_groupinvite_groupjoinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='房间名')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('friends', '好友可见'), ('group', '群成员可见')], default='public', max_length=16, verbose_name='可见性')),
                ('game_type', models.CharField(default='boardgame', max_length=64, verbose_name='游戏类型')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('playing', '对局中'), ('ended', '已结束')], default='waiting', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(blank=True, limit_choices_to={'type': 'group'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_rooms', to='chat.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '桌游室',
                'verbose_name_plural': '桌游室',
                'db_table': 'game_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRoomMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat', models.PositiveIntegerField(default=0, verbose_name='座位号')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='boardgame.gameroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '房间成员',
                'verbose_name_plural': '房间成员',
                'db_table': 'game_room_members',
                'ordering': ['seat', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['owner'], name='game_rooms_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['group'], name='game_rooms_group_idx'),
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['status'], name='game_rooms_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameroommember',
            unique_together={('room', 'user')},
        ),
    ]
